plugins {
    id("java")
    id("org.jetbrains.kotlin.jvm") version "2.1.20"
    id("org.jetbrains.intellij.platform") version "2.10.2"
}

group = "com.frshaka"
version = "1.0.2"

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdea("2025.2.4")
        testFramework(org.jetbrains.intellij.platform.gradle.TestFrameworkType.Platform)

        bundledPlugin("Git4Idea")

        implementation("com.squareup.okhttp3:okhttp:4.12.0")
        implementation("com.squareup.retrofit2:retrofit:2.12.0")
        implementation("com.squareup.moshi:moshi:1.15.2")
        implementation("com.squareup.moshi:moshi-kotlin:1.15.2")
        implementation("com.squareup.retrofit2:converter-moshi:2.12.0")
        implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.17.2")
    }
}

intellijPlatform {
    pluginConfiguration {
        ideaVersion {
            sinceBuild = "252.25557"
        }
        changeNotes = """
            <h2>New Features</h2>
            <ul>
                <li>
                    <b>Support for reasoning models (Chain-of-Thought).</b><br/>
                    Models such as DeepSeek-R1 and QwQ return an empty <code>content</code> field with an
                    internal reasoning object on intermediate steps. The plugin now handles this automatically:
                    it iterates through the Chain-of-Thought loop, accumulating the model's reasoning as context,
                    until a final <code>content</code> is produced. A safety limit of 8 iterations prevents
                    infinite loops.
                </li>
            </ul>
            <h2>Bug Fixes</h2>
            <ul>
                <li>
                    <b>Commit message field is now correctly cleared after a successful commit.</b><br/>
                    Previously, the message generated by the plugin would remain in the commit panel even after
                    committing. The cleanup now runs at the right point in IntelliJ's post-commit lifecycle,
                    ensuring the field is always empty and ready for the next commit.
                </li>
                <li>
                    <b>File selection is now respected for newly created (unversioned) files.</b><br/>
                    When only files listed under "Unversioned Files" were checked in the commit panel, the plugin
                    was ignoring the selection and generating a message based on all staged changes instead.
                    The plugin now correctly reads the content of unversioned files directly from disk and builds
                    a proper diff representation for them, scoping the AI generation to exactly what was selected.
                </li>
                <li>
                    <b>Fixed file path resolution for selected files on Windows.</b><br/>
                    File paths provided by IntelliJ's VFS use forward slashes and absolute references, while
                    Git's index stores relative paths. This mismatch caused the path filter to silently fall back
                    to a full diff. Paths are now relativized against the repository root before being passed to
                    <code>git diff</code>, ensuring correct filtering for all file types and operating systems.
                </li>
            </ul>
            <h2>Improvements</h2>
            <ul>
                <li>
                    <b>Comprehensive user manual added to the plugin description.</b><br/>
                    The plugin page on JetBrains Marketplace and the Settings &#8594; Plugins panel now include
                    a full step-by-step guide covering initial setup, daily usage, commit message format
                    reference, and a troubleshooting section.
                </li>
            </ul>
        """.trimIndent()
    }

    pluginVerification {
        ides {
            recommended()
        }
    }

    publishing {
        // Token do Marketplace (criado no perfil do JetBrains Marketplace)
        // Melhor pr�tica: injetar por vari�vel de ambiente/Gradle property, n�o hardcode.
        token.set(
            providers.environmentVariable("JB_MARKETPLACE_TOKEN")
                .orElse(providers.gradleProperty("jbMarketplaceToken"))
        )

        // Para release normal no canal default:
        channels.set(listOf("default"))

        // Se quiser soltar beta/alpha primeiro, troca para:
        // channels.set(listOf("alpha"))

        // Opcional: publicar como hidden (n�o aparece publicamente ap�s aprova��o).
        // hidden.set(true)
    }

    // Assinatura � opcional aqui.
    // Se voc� for assinar depois, a pr�pria doc do plugin mostra as op��es suportadas.
    // signing { ... }
}
tasks {
    withType<JavaCompile> {
        sourceCompatibility = "21"
        targetCompatibility = "21"
        options.encoding = "UTF-8"
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
    }
}